version: "3.4"

services:
  #my-nginx-service:
  #  image: nginx
  #  container_name: nginx-service
  #  ports:
  #    - 8000:80
  #  environment:
  #    - FOO=bar
  #  logging:
  #    driver: loki
  #    options:
  #      loki-url: http://localhost:3100/loki/api/v1/push
  #      loki-external-labels: job=dockerlogs,owner=aegis,environment=development
  #  restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    user: "0:0"
    environment:
      - ./env/configuration.env
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - /etc/timezone:/etc/timezone:ro
    - ./env/grafana.ini:/etc/grafana/grafana.ini
    - ./grafana/storage:/var/lib/grafana
    - ./grafana/provisioning:/etc/grafana/provisioning
    - ./grafana/dashboards:/etc/grafana/dashboards
    - ./config/datasource.yml:/etc/grafana/datasource.yml
    ports:
    - "3000:3000"
    restart: unless-stopped

  loki:
   image: grafana/loki:latest
   container_name: loki
   user: "0:0"
   volumes: 
     - /etc/localtime:/etc/localtime:ro
     - /etc/timezone:/etc/timezone:ro
     - ./config/config.yaml:/config/config.yaml
     - ./loki/loki-data:/tmp/loki
     - ./loki/loki-wal:/tmp/wal
   entrypoint:
     - /usr/bin/loki
     - config.file=./config/config.yaml
   ports:
     - "3100:3100"
   restart: unless-stopped

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    user: "0:0"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /var/lib/docker/containers:/var/lib/docker/containers
      - /var/log/auth.log:/var/log/auth.log
      - /var/log:/var/log
      - ./config/promtail-config.yml:/etc/config/promtail-config.yml
    entrypoint:
      - /usr/bin/promtail
      - -config.file=/etc/config/promtail-config.yml
    ports:
      - "9080:9080"
    restart: unless-stopped


  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    ports:
      - "9090:9090"
    restart: unless-stopped

  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    restart: unless-stopped
    ports:
      - "9093:9093"
    volumes:
      - "./config:/config"
      - ./alertmanager:/data
    command: --config.file=/config/alertmanager.yml --log.level=debug  

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
#      - '--collector.filesystem.ignored-fs-types="^(sys|proc|auto|cgroup|devpts|ns|au|fuse\.lxc|mqueue)(fs|)$$"'
    ports:
      - "9100:9100"
    restart: unless-stopped  

  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - '8086:8086'
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./influxdb-storage:/var/lib/influxdb2:rw
    environment:
      - ./env/fluxdb.ini:/etc/fluxdb.ini
    restart: unless-stopped   

#  reporter:
#    image: registry.gitlab.com/irtec/grafana-report:1.1.0
#    container_name: report
#    command: -ip=10.22.12.4:3000
#    volumes:
#      - /etc/localtime:/etc/localtime:ro
#      - /etc/timezone:/etc/timezone:ro
#    restart: unless-stopped

  renderer:
    image: grafana/grafana-image-renderer:latest
    container_name: render
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    restart: unless-stopped
 
  cadvisor:
    image: gcr.io/google-containers/cadvisor:v0.36.0
    container_name: cadvisor
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    ports:
      - "8080:8080"
    restart: unless-stopped
    
  jaeger:
    image: jaegertracing/all-in-one:1.30.0
    container_name: jaegertracing
    user:"0:0"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./jaeger:/badger
    mem_limit: 512m
    environment:
      - SPAN_STORAGE_TYPE=badger
      - BADGER_EPHEMERAL=false
      - BADGER_DIRECTORY_KEY=/badger/key
      - BADGER_DIRECTORY_VALUE=/badger/data
      - BADGER_SPAN_STORE_TTL=168h0m0s
    ports: ["6831:6831/udp", "6832:6832/udp", "14250:14250", "14269:14269", "16686:16686"]
    restart: unless-stopped  

  opentelemetry-collector:
    image: otel/opentelemetry-collector:0.58.0
    container_name: otel
    command: --config=/conf/otel-collector.yaml
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./config/otel-collector.yaml:/conf/otel-collector.yaml
    ports: ["9464:9464", "55680:55680", "55681:55681"] 
    restart: unless-stopped